Build app logic
hpham2687/Blog-React-App pull request #4
Opened 2022-01-09 09:19 UTC by hpham2687

- Add msw api for all route
- Add logic for auth 
- Add logic for add/edit/remove post
- Add logic for show posts, load more at home/manage page
- Add logic search at home page
- Add logic user can edit post at detail page

2022-01-10 05:13 UTC, nvh95 requested changes
- Form validation should be change to `onChange` mode
- Image should not be require when create a new post
- It flash when there is no post to show
- Should have `Add a new post` feature in Post list as well
- If users log out then log in, they cannot edit or delete their posts at `/`
- store should be in `store/index.js`
- Avoid using try catch when calling API
- Need to handle when api returns error
- Install code spell checker to check English grammar

2022-01-10 05:13 UTC, nvh95 commented on src/components/AddPost/index.js
> +    history("/manage");
If `createPostsAction` fails, I don't think it's a great idea to push to `/manage`

2022-01-10 05:13 UTC, nvh95 commented on src/components/Banner/Banner.js
> +        src="https://res.cloudinary.com/practicaldev/image/fetch/s--8G3GSc8q--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/vahl9y
I think we can host our own images in the scope of this project

2022-01-10 05:13 UTC, nvh95 commented on src/components/common/PostForm.js
> +  const isHasTitlenameError = errors?.title;
`TitleName`

2022-01-10 05:13 UTC, nvh95 commented on src/components/common/PostForm.js
> +  background: url(https://img.freepik.com/free-vector/hand-painted-watercolor-pastel-sky-background_23-2148902771.jpg?size=626&ext=jpg);
please host your own image

2022-01-10 05:13 UTC, nvh95 commented on src/components/common/PostForm.js
> +  }, [data, reset]);
Why do we need to do this?

2022-01-10 05:13 UTC, nvh95 commented on src/components/EditPost/index.js
> +        notifyPositive({ message: "Edit post sucessfully." });
`sucessfully`: typo

2022-01-10 05:13 UTC, nvh95 commented on src/store/reducers/postsReducer.js
> +      notifyPositive({ message: `Delete post ${postId} sucessfully.` });
`sucessfully`: typo

2022-01-10 05:13 UTC, nvh95 commented on src/store/reducers/postsReducer.js
> +      const response = await UserApi.getPosts(page, items_per_page, search);
Is it possible that we do not use try catch?

2022-01-10 06:48 UTC, nvh95 commented on src/App.js
> +import RegisterPage from "./components/Register";
Place `App.js` in components

2022-01-10 06:50 UTC, hpham2687 commented on src/App.js
> +          <Router navigator={history}>
remove history

2022-01-10 06:51 UTC, nvh95 commented on src/api/postApi.js
> +}
use fetch

2022-01-10 06:51 UTC, hpham2687 commented on src/api/postApi.js
> +function getPostDetail(postId) {
change axios to fetch

2022-01-17 10:10 UTC, nvh95 approved these changes

2022-01-17 10:10 UTC, merged